```{r}
#Question 2 & 3
library(dplyr)
library(tidyr)
library(tidyverse)
#reading in the csvs
brewery = read.csv(file.choose(),header = TRUE)
beer = read.csv(file.choose(),header = TRUE)

#renaming columns for the join to the beer dataset
brewery=rename(brewery, Brewery_id=Brew_ID, Brewery=Name)
brewery$State <- trimws(brewery$State, which = c("left"))#added to remove space before state

#pulling ids with inaccurate info
Brewery_id<-as.integer(c(96,415,167, 262, 139))
error_brew_ids<-as.data.frame(Brewery_id)
#joining to get Brewery Names
brew_filter = merge(x=error_brew_ids,y=brewery,by="Brewery_id") %>% select(Brewery_id, Brewery)

#joining on brewery name to pull in correct columns--filter out inaccurate
brew_filter = merge(x=brewery,y=brew_filter,by="Brewery") %>% mutate(type = case_when( Brewery_id.x==Brewery_id.y ~ "correct",TRUE~  "wrong"))
#filtering down to rows with errors
brew_replace =brew_filter %>%filter(type == "wrong") %>% select(Brewery_id.y, Brewery, City, State)%>% rename(Brewery_id=Brewery_id.y)

#removing errors and replacing with updated df
brewery = anti_join(x=brewery,y=error_brew_ids,by="Brewery_id")
brewery<-rbind(brewery, brew_replace)
brewery$City = str_replace(brewery$City, "Menominie", "Menomonie")

#join between brewery and beer data
beer_brewery = merge(x=brewery,y=beer,by="Brewery_id")

#print first 6 rows
head(beer_brewery)
#print last 6 rows
tail(beer_brewery)

#filtering of NAs for ABV and IBU-- rows drop from 2410 down to 1405 for this filtering
#only use this filtered dataset for the questions related to ABV/IBU
clean_beer_brewery <- beer_brewery %>% filter_at(vars(ABV,IBU),all_vars(!is.na(.)))
```


```{r}
#question 1 (and possibly part of 9)
#How many breweries are present in each state? (counties heatmap)
#load libraries
library(ggplot2)
library(maps)
#library(tidyverse)#added to 1st chunk
library(ggthemes)
library(kableExtra)
#load counties table
cnty <- read.csv("cty-cnty.csv")
colnames(cnty)[3] <- "region"
#load population data 2021
pop_est <- read.csv("NST-EST2021-alldata.csv")
pop_est <- pop_est %>% select(NAME,POPESTIMATE2021) %>% rename(region=NAME, "Pop2021"=POPESTIMATE2021) %>% mutate(region=tolower(region))
pop_est <- pop_est[-c(1:5),]
pop_est$region %>% str_replace("District of Columbia", "washington, d.c.")
pop_est$rank <- rank(-pop_est$Pop2021)

#data wrangle
#brewery$State <- trimws(brewery$State, which = c("left"))
cnty <- cnty %>% select("City", "State","County","region")#select columns
cnty <- cnty[!duplicated(cnty),]


#left join brew and cnty
brewcomb <- merge(brewery, select(cnty, c("City", "State", "County","region")), by=c("City","State"))
brewcomb <- brewcomb %>% distinct(Brewery_id, .keep_all = TRUE)

#1 table wtih state count, map with state count and map with county count
#state and county tables
us_states <- map_data("state")
us_counties <- map_data("county")

#state brewery count
brew_state <- brewcomb %>% mutate(region=tolower(region)) %>%
  group_by(region) %>% count(region)
brew_state <- brew_state %>% left_join(pop_est,by="region") %>% arrange(desc(n))
brew_state %>% mutate(region=str_to_title(region),Pop2021=round(Pop2021/1000000,2)) %>% kable(col.names = c("State","Breweries","Population 2021","Pop. Rank")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")
#state gradient map
us_states %>% left_join(brew_state,by=("region")) %>% 
  ggplot(aes(x=long,y=lat,group=group,fill=n))+
  geom_polygon(color = "gray90", size=.1)+
  coord_map(projection = "albers", lat0=45, lat1=55)+
  scale_fill_viridis_c()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        axis.title = element_blank())+
  labs(fill="Brewery\nCount")+
  ggtitle("Breweries by State\nContinental US")
  
#county brewery count
brew_county <- brewcomb %>% mutate(subregion=tolower(County)) %>% 
  group_by(subregion) %>% count(subregion)
#county gradient map
us_counties %>% left_join(brew_county,by="subregion") %>%
  ggplot()+
  geom_polygon(aes(x=long,y=lat,group=group,fill=n),color = "gray90",size=.1)+
  coord_map(projection = "albers",lat0=45,lat1=55)+
  scale_fill_viridis_c()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        axis.title = element_blank())+
  labs(fill="Brewery\nCount")+
  ggtitle("Breweries by County\nContinental US")+
  geom_polygon(data = us_states,aes(x=long,y=lat,group=group), color = "white",size=.15,fill="transparent")
```

```{r}
#Question 4
#Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.

#ABV
bb<-clean_beer_brewery %>% group_by(State) %>% summarize(medianABV = median(ABV), count = n()) %>% ggplot(aes(x = reorder(State, -medianABV), y = medianABV, fill=medianABV)) + geom_col()+ 
  xlab('State') + ylab('Median ABV')+ggtitle("Median ABV by State") +theme(axis.text = element_text(size = 6))+ scale_fill_gradient(low='#46085C', high='#4FBA6E', name='Median ABV')
bb + scale_y_continuous(labels = scales::percent)

#IBU
bb<-clean_beer_brewery %>% group_by(State) %>% summarize(medianABV = median(ABV), medianIBU=round(median(IBU),0), count = n()) %>% ggplot(aes(x = reorder(State, -medianABV), y = medianIBU, fill=medianIBU)) + geom_col()+ 
  xlab('State') + ylab('Median IBU')+ggtitle("Median IBU by State") +theme(axis.text = element_text(size = 6))+ scale_fill_gradient(low='#46085C', high='#4FBA6E', name='Median IBU')
bb 

#combined
bb<-clean_beer_brewery %>% group_by(State) %>% summarize(medianABV = median(ABV), medianIBU=round(median(IBU),0), count = n()) %>% ggplot(aes(x = reorder(State, -medianABV), y = medianABV, fill=medianIBU)) + geom_col()+ 
  xlab('State') + ylab('Median ABV')+ggtitle("Median IBU/ABV by State") +theme(axis.text = element_text(size = 6))+ scale_fill_gradient(low='#46085C', high='#4FBA6E', name='Median IBU')
bb + scale_y_continuous(labels = scales::percent)
```

```{r}
#5 which state has the maximum alcoholic (ABV) beer? which state has the most bitter (IBU) beer?
maxABV <- beer_brewery %>% merge(cnty, by=c("City", "State")) %>% select(ABV, region) %>% 
  filter(!is.na(ABV)) %>% group_by(region) %>% summarise(Max_ABV=max(ABV)) %>% arrange(desc(Max_ABV))
maxABV %>% kable(col.names = c("State", "Max ABV")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")

maxIBU <- beer_brewery %>% merge(cnty, by=c("City", "State")) %>% select(IBU, region) %>% 
  filter(!is.na(IBU)) %>% group_by(region) %>% summarise(Max_IBU=max(IBU)) %>% arrange(desc(Max_IBU))
maxIBU %>% kable(col.names = c("State","Max IBU")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")

us_states %>% mutate(region=str_to_title(region)) %>% left_join(maxABV,by="region") %>% 
  ggplot(aes(x=long,y=lat,group=group, fill = Max_ABV))+
  geom_polygon(color = "gray90", size=.1)+
  coord_map(projection = "albers", lat0=45, lat1=55)+
  scale_fill_viridis_c()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        axis.title = element_blank())+
  labs(fill="Maximum\nAlcohol by Volume")+
  ggtitle("Maximum ABV by State\nContinental US")

us_states %>% mutate(region=str_to_title(region)) %>% left_join(maxIBU,by="region") %>% 
  ggplot(aes(x=long,y=lat,group=group, fill = Max_IBU))+
  geom_polygon(color = "gray90", size=.1)+
  coord_map(projection = "albers", lat0=45, lat1=55)+
  scale_fill_viridis_c()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        panel.background = element_blank(),
        axis.title = element_blank())+
  labs(fill="Maximum\nIBU")+
  ggtitle("Maximum IBU by State\nContinental US")

```

```{r}
#Question 6
#6 comment on the summary statistics and distribution of the ABV variable
beer_brewery %>% ggplot(aes(x=Beer_ID,y=ABV, color=as.factor(Ounces)))+geom_point()+scale_color_viridis_d()+theme_bw()+labs(color="Ounces")+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        panel.border = element_blank())
beer_brewery %>% ggplot(aes(x=ABV))+geom_density(color="#39568C")+theme_bw()+theme(
  panel.grid = element_blank(),
  panel.border = element_blank())
beer_brewery %>% ggplot(aes(x=ABV))+geom_boxplot()
ABVsum <- beer_brewery %>% filter(!is.na(ABV)) %>% 
  select(ABV) %>%
  summarise(min=min(ABV),
            "25%"=quantile(ABV,.25),
            median=median(ABV),
            "75%"=quantile(ABV,.75),
            max=max(ABV),mean=mean(ABV))
ABVsum %>% kable(col.names = c("Min", "25%", "Med", "75%", "Max", "Mean")) %>% 
  kable_styling(latex_options = c("striped", "scale_down")) %>% 
  row_spec(row = 0, italic = T, background = "#21918c", color = "white") %>% 
  column_spec(1:2, width = "0.5in")

#right skewed distribution centered at .057, there seems to be some degree of rounding occuring at around .1, 
#given that there are several beers that are exactly at the line with fewer slightly below and almost none 
#slightly above the number. There also seems to be some degree of rounding at .5, but this is less pronounced
```
```{r}
#Question 7
#7.Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot. Make your best judgment of a relationship and EXPLAIN your answer.

#comparison of ABV/IBU in scatter plot with regression line
bb = clean_beer_brewery %>% ggplot(aes(x = ABV, y=IBU, color = IBU)) + geom_point(aes(fill=IBU, color=IBU),pch=21,size=3,colour="black")+ ggtitle("International Bitterness Units vs. Alchohol by Volume")+ 
  geom_smooth(method='lm', formula= y~x, color="black")
bb + scale_x_continuous(labels = scales::percent)

```

```{r}
#Question 8
#Budweiser would also like to investigate the difference with respect to IBU and ABV between IPAs (India Pale Ales) and other types of Ale (any beer with “Ale” in its name other than IPA).  You decide to use KNN classification to investigate this relationship.  Provide statistical evidence one way or the other. You can of course assume your audience is comfortable with percentages … KNN is very easy to understand conceptually.

#add ipa, ale, other column
ipa_ale <-
  clean_beer_brewery %>% mutate(Ale_type = ifelse(
    str_detect(clean_beer_brewery$Style, regex("ipa", ignore_case = TRUE)),
    "IPA",
    ifelse(str_detect(
      clean_beer_brewery$Style, regex("ale", ignore_case = TRUE)
    ), "Ale", "other")
  ))
#filter out "other" type of beers and drop levels
ipa_ale <- ipa_ale %>% filter(Ale_type %in% c("IPA", "Ale")) %>% droplevels(ipa_ale$Ale_type)

#for loops for KNN model and hypertuning k parameter
nsplits <- 100
nks <- 30

df <- data.frame()
set.seed(6)
for (i in 1:nsplits) {
  n <- nrow(ipa_ale)
  nsamp <- sample(1:n,round(n*.7)) #for a 70-30 split
  ipa_train <- ipa_ale[nsamp,]
  ipa_test <- ipa_ale[-nsamp,]
  
  for (j in 1:nks) {
    cm <- knn(scale(ipa_train[,7:8]),scale(ipa_test[,7:8]),cl=ipa_train$Ale_type,k=i) %>% confusionMatrix(as.factor(ipa_test$Ale_type),positive = "IPA")
    cm_values <- data.frame("k"=j,"Accuracy"=cm$overall[1],"Sensitivity"=cm$byClass[1],"Specificity"=cm$byClass[2])
    df <- rbind(df,cm_values)
  }
}

#summarize the k results
means <- df %>% group_by(k) %>% summarise(Accuracy=mean(Accuracy)*100,Sensitivity=mean(Sensitivity)*100,Specificity=mean(Specificity)*100)

#plot accuracy, sensitivity and specificity
means %>% ggplot(aes(x=k,y=Accuracy))+geom_line(color="#39568C")+theme_bw()+theme(
  panel.grid = element_blank(),
  panel.border = element_blank())
means %>% ggplot(aes(x=k,y=Sensitivity))+geom_line(color="#39568C")+theme_bw()+theme(
  panel.grid = element_blank(),
  panel.border = element_blank())
means %>% ggplot(aes(x=k,y=Specificity))+geom_line(color="#39568C")+theme_bw()+theme(
  panel.grid = element_blank(),
  panel.border = element_blank())

#After hypertuning the k parameter, we can see that looking at the 14 closest beers in terms of ABV and IBU would help us make a prediction on whether it's a Indian Pale Ale or a nother type of Ale, with about 85% accuracy.
#Moreover, this model is able to properly classify IPAs 85.98% of the time
```
#```{r}
#Question 9
#Knock their socks off!  Find one other useful inference from the data that you feel Budweiser may be able to find value in.  You must convince them why it is important and back up your conviction with appropriate statistical evidence. 
#looking at binge drinking prevalence by state vs. ABV by state
cdc_beer_brewery = merge(x=clean_beer_brewery,y=CDC,by="State")
cdc_beer_brewery%>% rename(CDC.BNG=Binge.drinking.prevalence)

bb<-cdc_beer_brewery %>% group_by(State) %>% summarize(medianABV = median(ABV), BingeDrink=round(median(Binge.drinking.prevalence),0), count = n()) 

bb.lm <- lm(medianABV~ BingeDrink, bb)

bb = cdc_beer_brewery %>% ggplot(aes(x = ABV, y=Binge.drinking.prevalence, color = Binge.drinking.prevalence)) + geom_point(aes(fill=Binge.drinking.prevalence, color=IBU),pch=21,size=3,colour="black")+ ggtitle("ABV vs. Binge Drinking Prevalence")+ 
  geom_smooth(method='lm', formula= y~x, color="black")
bb + scale_x_continuous(labels = scales::percent)

#pulling tweets by location that mention budweiser
library(rtweet)

twitter_token <- create_token(
  app = appname,
  consumer_key = key,
  consumer_secret = secret,
  access_token = access_token,
  access_secret = access_secret,
  set_renv = TRUE)
  
budweiser_tweets <- search_tweets(q="budweiser",  n = 18000,
                                  include_rts = FALSE, lang = "en", 
                                  geocode = lookup_coords("usa")
loc=budweiser_tweets %>% filter(is.na(location) == FALSE & location != "" & location != "USA" & location != "United States"& location != "Canada") 
loc <- loc %>%
  group_by(location) %>% count(location)
loc %>% arrange(desc(n))
)

#recently popular tweets from budweiser
budweiserusa <- get_timeline("budweiserusa", n = 3200)
top_retweets <- budweiserusa %>% select(text, retweet_count, favorite_count) %>% filter(is.na(retweet_count) == FALSE & retweet_count!="")  %>% arrange(desc(retweet_count)) %>% top_n(10)

```




