---
title: "Unit 5 markdown"
author: "Miguel Bonilla"
date: "1/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(httr)
library(dplyr)
library(stringr)
library(tidyverse)
library(cowplot)
library(GGally)
library(ggthemes)
library(wordcloud2)
library(png)

```

#Part 1
```{r}
Bball <- read_csv("PlayersBBall.csv")

#Secondary Table with new columns for Height and Inches
Htab <- data.frame(Bball,str_split(Bball$height, "-", simplify = TRUE))
#New column with Height in Inches
Htab <- mutate(Htab, TotalInches = as.numeric(Htab$X1)*12+as.numeric(Htab$X2))
Htab$position <- as.factor(Htab$position)
#make histogram of positions
Htab %>% filter(position != is.na(position)) %>% ggplot(aes(TotalInches, fill = position))+geom_histogram()+facet_wrap(~position)+theme_hc()+scale_fill_solarized()+ggtitle("NBA Players Height Distribution\nby Position")

```
#Part 2
```{r}
Fifa <- read.csv("Fifaplayers.csv")

#add columns for height and weights
ftab <- data.frame(Fifa, Heightft=str_split(Fifa$Height, "'", simplify = TRUE),Weightlbs=as.numeric(str_sub(Fifa$Weight, 0,-4)))

#mutate to add total inches
ftab <- ftab %>% mutate(HeightFt = as.numeric(ftab$Heightft.1)+as.numeric(ftab$Heightft.2)/12)

ftab <- ftab %>% 
  mutate(PositionGroup = case_when(
    Position %in% c("ST", "RF", "LF", "CF", "LW", "RW", "RS", "LS") ~ "Forward",
    Position %in% c("RCM", "LCM", "LDM", "CAM", "CDM", "RM", "LAM", "LM", "RDM", "CM", "RAM") ~ "Midfielder",
    Position %in% c("RCB", "CB", "LCB", "LB", "RB", "RWB", "LWB") ~ "Defender",
    Position == "GK" ~ "Goalkeeper"
  ))

ftab %>% ggplot(aes(x = HeightFt, y = Weightlbs))+geom_jitter(aes(color = PositionGroup))+labs(x = "Height in ft.", y = "Weight in lbs.")+geom_smooth()+theme_hc()+scale_color_solarized()+facet_wrap(~PositionGroup)

ftab %>% select(HeightFt,Weightlbs,PositionGroup) %>%
  ggpairs(aes(color = PositionGroup, alpha = .75))+
  theme_hc(base_size = 8)+scale_color_solarized()

ftab %>% filter(Position == "LB"|Position == "LM") %>% ggplot(aes(x = HeightFt, y = Weightlbs))+geom_point(aes(color = Position))+theme_hc()+scale_color_solarized()+facet_wrap(~Position)+geom_smooth()

```

#Part 3
```{r}
#Question 1A
df <- read_delim("yob2016.txt", delim = ";", col_names = c("Name", "Sex", "Count"), col_types = c("Sex" = "factor"))
#Display the summary and structure of df
df
str(df)
#look for repeated misspelled name

df %>% filter(str_detect(df$Name,"yyy$"))
y2016 <- df %>% filter(Name != "Fionayyy")



```



```{r}
#Question 2
#Import
y2015<- read.csv("yob2015.txt", col.names = c("Name", "Sex", "Count"), colClasses = c("Sex" = "factor"), header = FALSE)
#display the last ten rows
tail(y2015, n = 10)
#Merge
final <- merge(y2015,y2016, by = c("Name", "Sex"))
final
```


```{r}
#Question 3
final <- final %>% mutate(Total = Count.x+Count.y)

#sort
final <- final %>% arrange(desc(Total))

final %>% head(n = 10) %>% select(Name, Total)
final %>% head(n = 10) %>% ggplot(aes(x = fct_reorder(Name,Total,.desc = TRUE), y = Total, fill = Sex))+geom_col()+theme_hc()+scale_fill_solarized()+labs(x = "Name")

#omit boys
top10girls <- final %>% filter(Sex =="F") %>% head(n=10) %>% select(Name,Total,Sex)

top10girls %>% ggplot(aes(x = fct_reorder(Name,Total,.desc = TRUE), y = Total, fill = Sex))+geom_col()+theme_hc()+scale_fill_solarized()+labs(x = "Name")


#write the top10 names to a csv file
write_csv(top10girls, "top10girls.csv")
```

```{r}
#Question 4
#create a visual result
#long form
top10names <- final %>% head(n=10) %>% select(Name)


paste(top10names)

flonger <- final %>%
  head(n=10) %>% 
  select(Name, Sex,"2015" = Count.x,"2016" =Count.y) %>% 
  filter(Name %in% c("Emma", "Olivia", "Noah", "Liam", "Sophia", "Ava", "Mason", "William", "Jacob","Isabella")) %>% 
  pivot_longer(cols = -c("Name", "Sex"),names_to = "Year", values_to = "Total")

flonger %>% ggplot(aes(x = Name, y = Total, fill = Year)) +geom_col(aes(color = Sex),size = 1)+theme_hc()+scale_fill_hc()+scale_color_discrete()+ggtitle("Top 10 Baby Names for 2015 & 2016")

final %>% select(Name,Total) %>% wordcloud2()
```

